apiVersion: v1
kind: Service
metadata:
  name: teastore-db
  labels:
    app: teastore
    run: teastore-db
spec:
  ports:
    - port: 3306
      protocol: TCP
      # appProtocol: TCP
      name: tcp-teastore-db
  selector:
    run: teastore-db
